# Generated by Django 4.2.3 on 2023-07-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='age',
            field=models.CharField(default='', max_length=25),
        ),
    ]
