# Generated by Django 4.2.3 on 2023-07-25 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_city_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='age',
        ),
    ]
